language: elixir

matrix:
  include:
    - elixir: 1.7.4
      otp_release: 20.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.7.4
      otp_release: 21.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.7.4
      otp_release: 22.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.8.2
      otp_release: 20.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.8.2
      otp_release: 21.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.8.2
      otp_release: 22.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.9.4
      otp_release: 20.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.9.4
      otp_release: 21.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.9.4
      otp_release: 22.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.10.4
      otp_release: 21.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.10.4
      otp_release: 22.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.10.4
      otp_release: 23.0
      env: PROTOBUF_PACKAGE=protobuf
    # additional checks
    - elixir: 1.10.4
      otp_release: 23.0
      install: skip
      script: mix format --check-formatted --dry-run
      env: FORMATTER=true # only as label in travis
    - elixir: 1.8.0
      otp_release: 21.2
      env: PROTOBUF_PACKAGE=exprotobuf
