language: elixir

matrix:
  include:
    - elixir: 1.4.5
      otp_release: 18.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.4.5
      otp_release: 19.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.4.5
      otp_release: 20.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.5.3
      otp_release: 18.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.5.3
      otp_release: 19.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.5.3
      otp_release: 20.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.6.6
      otp_release: 19.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.6.6
      otp_release: 20.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.6.6
      otp_release: 21.2
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.7.4
      otp_release: 19.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.7.4
      otp_release: 20.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.7.4
      otp_release: 21.2
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.8.0
      otp_release: 20.3
      env: PROTOBUF_PACKAGE=protobuf
    - elixir: 1.8.0
      otp_release: 21.2
      env: PROTOBUF_PACKAGE=protobuf
    # additional checks
    - elixir: 1.8.0
      otp_release: 21.2
      install: skip
      script: mix format --check-formatted --dry-run
      env: FORMATTER=true # only as label in travis
    - elixir: 1.8.0
      otp_release: 21.2
      env: PROTOBUF_PACKAGE=exprotobuf
