name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - 1.11-slim
          - 1.12-slim
          - 1.13-slim
          - 1.14-slim
    container:
      image: elixir:${{ matrix.elixir }}
    env:
      MIX_ENV: test
      PROTOBUF_PACKAGE: protobuf
    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        apt-get update
        apt-get install build-essential -y
    - name: tests
      run: mix test

  test_exprotobuf:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.12-slim
    env:
      MIX_ENV: test
      PROTOBUF_PACKAGE: exprotobuf
    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        apt-get update
        apt-get install build-essential -y
    - name: tests
      run: mix test

  format:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.14-slim
    steps:
    - uses: actions/checkout@v2
    - name: format
      run: mix format --check-formatted --dry-run
